
CREATE TABLESPACE mid_term 
DATAFILE 'mid_term.DBF' 
SIZE 20M ;

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;  

CREATE PROFILE parcial LIMIT
PASSWORD_LIFE_TIME 100 
SESSIONS_PER_USER 1 
IDLE_TIME 20 
FAILED_LOGIN_ATTEMPTS 2;  
    
    
CREATE USER yzuleta
IDENTIFIED BY yzuleta 
DEFAULT TABLESPACE mid_term
PROFILE parcial
QUOTA UNLIMITED ON mid_term;


CREATE USER rrendon
IDENTIFIED BY rrendon 
DEFAULT TABLESPACE mid_term
PROFILE parcial;

CREATE ROLE MINI_DBA
NOT IDENTIFIED;
GRANT CREATE TABLE, CREATE VIEW TO MINI_DBA;
GRANT CREATE SESSION TO MINI_DBA;

CREATE ROLE STUDENT
NOT IDENTIFIED;
GRANT CREATE SESSION TO STUDENT;
    
GRANT MINI_DBA TO yzuleta;

CREATE TABLE BARRIOS( 
    ID NUMBER(22,0) NOT NULL, 
    NOMBRE VARCHAR(255) NOT NULL, 
    COMUNA_ID NUMBER(22,0) NOT NULL, 
    PRIMARY KEY (ID),
    FOREIGN KEY (COMUNA_ID) REFERENCES COMUNAS(ID)
)TABLESPACE mid_term;


CREATE TABLE COMUNAS( 
    ID NUMBER(22,0) NOT NULL,  
    NOMBRE VARCHAR(255) NOT NULL, 
    TIPO_COMUNA_ID NUMERIC,
    PRIMARY KEY (ID),
    FOREIGN KEY (TIPO_COMUNA_ID) REFERENCES TIPO_COMUNAS(ID) 
)TABLESPACE mid_term; 
  

CREATE TABLE TIPO_COMUNAS( 
    ID NUMBER(22,0) NOT NULL,  
    TIPO VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
)TABLESPACE mid_term;
  

CREATE TABLE ESTADOS_PRESENTADORES( 
    ID NUMBER(22,0) NOT NULL, 
    NOMBRE VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
)TABLESPACE mid_term; 
  

CREATE TABLE PRESENTADORES(
    ID NUMBER(22,0) NOT NULL,  
    NOMBRE VARCHAR(255) NOT NULL, 
    FECHA_CONTRATACION DATE NOT NULL, 
    VALOR_CONTRATO NUMERIC NOT NULL, 
    ESTADO_ID NUMERIC, 
    PRIMARY KEY (ID),
    FOREIGN KEY (ESTADO_ID) REFERENCES ESTADOS_PRESENTADORES (ID)
)TABLESPACE mid_term; 


CREATE TABLE MODALIDADES( 
    ID NUMBER(22,0) NOT NULL,  
    NOMBRE VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
)TABLESPACE mid_term;  


CREATE TABLE SEDES(
    ID  NUMBER(22,0) NOT NULL, 
    SEDE VARCHAR(255) NOT NULL, 
    TELEFONO VARCHAR(255) NOT NULL, 
    DIRECCION VARCHAR(255) NOT NULL, 
    CUPOS_DISPUESTOS NUMERIC NOT NULL,
    BARRIO_ID NUMERIC NOT NULL, 
    MODALIDAD_ID NUMERIC NOT NULL, 
    PRESENTADOR_ID NUMERIC NOT NULL, 
    PRIMARY KEY (ID),
    FOREIGN KEY (BARRIO_ID) REFERENCES BARRIOS (ID), 
    FOREIGN KEY (MODALIDAD_ID) REFERENCES MODALIDADES (ID), 
    FOREIGN KEY (PRESENTADOR_ID) REFERENCES PRESENTADORES (ID) 
)TABLESPACE mid_term;

CREATE VIEW query_I 
 AS (
 SELECT MODA.NOMBRE FROM 
 MODALIDADES MODA INNER JOIN SEDES SED
 ON MODA.ID = SED.ID
 ORDER BY ASC
 )
 




